const state = { pending: null, queue: [], ledger: [], records: [], imageData: null, user: null };
async function sha256(text){try{const buf=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text));return [...new Uint8Array(buf)].map(b=>b.toString(16).padStart(2,'0')).join('')}catch(e){return null}}
const statusLabel = (x) => x.status === 'approved' ? '已入账' : x.status === 'rejected' ? '已拒绝' : '待审核';
const ACCOUNTS = { admin:{password:'admin123',role:'admin',name:'Aina'}, finance:{password:'fin123',role:'admin',name:'Finance Admin'}, employee:{password:'emp123',role:'employee',name:'员工'}, staff2:{password:'staff123',role:'employee',name:'员工 2'} };
const BASE_INCOME = 24800, BASE_CASH = 35400;
const demoReceipts = {
  normal: { vendor: 'Grab Malaysia Sdn. Bhd.', date: '2026-08-11', invoiceNumber: 'GRAB-28491', total: 38.5, tax: 0, currency: 'MYR', category: 'Travel & Transport', description: 'Grab business ride', confidence: 96, myinvoisStatus: 'Reference detected' },
  lowconf: { vendor: 'Street Mart Mini Market', date: '2026-08-12', invoiceNumber: 'SM-8821', total: 12.9, tax: 0, currency: 'MYR', category: 'Other Expenses', description: '模糊收据，AI 置信度低', confidence: 42, myinvoisStatus: 'Not verified' },
  duplicate: { vendor: 'Grab Malaysia Sdn. Bhd.', date: '2026-08-11', invoiceNumber: 'GRAB-28491', total: 38.5, tax: 0, currency: 'MYR', category: 'Travel & Transport', description: '重复提交的同一张收据', confidence: 95, myinvoisStatus: 'Reference detected' },
};
const waReceipt = { vendor: "McDonald's Malaysia (WhatsApp 模拟)", date: '2026-08-13', invoiceNumber: 'MCD-WA-0412', total: 26.9, tax: 0, currency: 'MYR', category: 'Meals & Entertainment', description: 'WhatsApp 收图（模拟）', confidence: 88, myinvoisStatus: 'Reference detected' };
const resubmitable = (r) => ['vendor','date','invoiceNumber','total','tax','currency','category','description','confidence','myinvoisStatus'].filter(k=>k in r).reduce((o,k)=>(o[k]=r[k],o),{});
const $ = (s) => document.querySelector(s);
const esc = (t) => String(t ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const riskLabel = (x) => x.risk === 'approved' ? '通过' : x.risk === 'rejected' ? '高风险' : '待复核';
const money = (n) => `RM ${Number(n).toLocaleString('en-MY',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const api=async(path,options={})=>{const headers={'Content-Type':'application/json',...(options.headers||{})};if(state.user?.token)headers.Authorization=`Bearer ${state.user.token}`;const r=await fetch(path,{...options,headers});if(!r.ok)throw new Error((await r.json().catch(()=>({}))).error||'后端请求失败');return r.json()};
async function refreshNotifications(){if(!state.user)return;const ns=await api('/api/notifications');const unread=ns.filter(x=>!x.read);if(unread.length)toast(unread[0].message);if(unread.length)await api('/api/notifications/read',{method:'POST',body:'{}'})}
async function loadRecords(){if(!state.user)return;const records=await api('/api/receipts');state.records=records;state.queue=records.filter(r=>r.status==='pending');state.ledger=records.filter(r=>r.status==='approved');if(state.user.role==='admin'){const keep=state.pending&&state.queue.some(r=>r.id===state.pending.id);state.pending=keep?state.pending:(state.queue[0]||null);}updateDashboard();}
function applyRole(){const isAdmin=state.user?.role==='admin';document.body.classList.toggle('locked',!state.user);document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('hidden-nav',!isAdmin&&!['upload','myreceipts'].includes(b.dataset.view)));document.querySelectorAll('.admin-only').forEach(b=>b.classList.toggle('hidden-nav',!isAdmin));$('#open-settings').classList.toggle('hidden-nav',!isAdmin);if(state.user){$('.profile').textContent=state.user.name.slice(0,2).toUpperCase();setView(isAdmin?'dashboard':'upload')}}
async function login(){const u=$('#login-username').value.trim().toLowerCase(),p=$('#login-password').value;try{state.user=await api('/api/login',{method:'POST',body:JSON.stringify({username:u,password:p})});await loadRecords();$('#login-screen').style.display='none';applyRole();await refreshNotifications();toast('登录成功。')}catch(e){$('#login-error').textContent=e.message}}
$('#login-button').addEventListener('click',login);$('#login-password').addEventListener('keydown',e=>e.key==='Enter'&&login());$('#logout-button').addEventListener('click',async()=>{try{await api('/api/logout',{method:'POST',body:'{}'})}catch{}state.user=null;state.pending=null;state.queue=[];$('#login-screen').style.display='grid';document.body.classList.add('locked')});

function setView(view) { if(!state.user)return;if(state.user.role!=='admin'&&!['upload','myreceipts'].includes(view)){toast('员工账号只能访问上传收据与我的收据页面。');view='upload'}document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===view));$('#'+view).classList.add('active');const titles={dashboard:'早上好，Aina',upload:'上传新收据',myreceipts:'我的收据',review:'审核中心',reports:'财务报表',admin:'数据管理'};$('#page-title').textContent=state.user.role==='employee'&&view==='upload'?'上传收据':titles[view];if(view==='review')loadRecords().then(renderReview);if(view==='reports')renderReports();if(view==='myreceipts')loadRecords().then(renderMyReceipts);if(view==='admin')loadRecords().then(renderAdmin);window.scrollTo({top:0,behavior:'smooth'}); }
document.querySelectorAll('[data-view],[data-go]').forEach(el=>el.addEventListener('click',()=>setView(el.dataset.view||el.dataset.go)));
$('#wa-demo').addEventListener('click',async()=>{try{const saved=await api('/api/receipts',{method:'POST',body:JSON.stringify(waReceipt)});state.queue.unshift(saved);if(state.records)state.records.unshift(saved);$('#wa-last').textContent='employee · 收据图片 · 刚刚';$('#wa-reply').textContent='已模拟入队：该单据已通过 /api/receipts 真实写入队列，管理员可在审核中心查看。';toast('WhatsApp 模拟收据已真实进入审核队列。')}catch(e){toast(e.message||'提交失败，请先登录。')}});

function categoryLabel(c){return ({'Travel & Transport':'交通与差旅','Meals & Entertainment':'餐饮与招待','Office Supplies':'办公用品','Software & Subscriptions':'软件订阅','Fixed Assets':'固定资产','Other Expenses':'其他费用'})[c]||c}
function expenseTotal(){ return state.ledger.reduce((sum,x)=>sum+x.total,0) }
function updateDashboard(){ const total=expenseTotal(), profit=BASE_INCOME-total, risks=state.ledger.filter(x=>x.risk!=='approved').length+state.queue.length; $('#expenses').textContent=money(total); $('#expense-note').textContent=total?'已确认 '+state.ledger.length+' 笔费用':'尚未确认费用'; $('#profit').textContent=money(profit); $('#risk-count').textContent=risks; $('#review-badge').textContent=state.queue.length; const cats={}; state.ledger.forEach(x=>cats[x.category]=(cats[x.category]||0)+x.total); $('#category-chart').innerHTML=Object.keys(cats).length?Object.entries(cats).map(([k,v])=>`<div class="category-row"><span>${categoryLabel(k)}</span><div class="bar"><i style="width:${v/total*100}%"></i></div><b>${money(v)}</b></div>`).join(''):'<p class="empty">确认收据后将显示支出分类。</p>'; $('#insights').innerHTML=total?`<p class="insight">✦ 本月已自动入账 ${state.ledger.length} 笔费用，共 ${money(total)}。最大支出类别是「${categoryLabel(Object.entries(cats).sort((a,b)=>b[1]-a[1])[0][0])}」。</p>`:'<p class="insight">上传收据后，AI 会识别、审核，并将建议直接写入总账。</p>'; $('#recent-list').innerHTML=state.ledger.length?state.ledger.slice(0,4).map(x=>`<div class="transaction"><span class="transaction-icon">▧</span><div><b>${x.vendor}</b><small>${x.date} · ${categoryLabel(x.category)}</small></div><strong>-${money(x.total)}</strong></div>`).join(''):'<p class="empty">还没有已入账交易。</p>' }

function setImage(file){ const reader=new FileReader(); reader.onload=e=>{state.imageData=e.target.result; $('#preview-image').src=e.target.result; $('#preview-image').hidden=false; $('#upload-placeholder').hidden=true; $('#analyze-button').disabled=false}; reader.readAsDataURL(file) }
$('#receipt-file').addEventListener('change',e=>e.target.files[0]&&setImage(e.target.files[0]));
$('#drop-zone').addEventListener('dragover',e=>e.preventDefault()); $('#drop-zone').addEventListener('drop',e=>{e.preventDefault(); if(e.dataTransfer.files[0]) setImage(e.dataTransfer.files[0])});
$('#demo-receipt').addEventListener('click',()=>{state.imageData=null; $('#preview-image').hidden=true; $('#upload-placeholder').hidden=false; analyze(true,'normal')});
document.querySelectorAll('.demo-btn').forEach(b=>b.addEventListener('click',()=>{state.imageData=null; $('#preview-image').hidden=true; $('#upload-placeholder').hidden=false; analyze(true,b.dataset.demo)}));
$('#analyze-button').addEventListener('click',()=>analyze(false));

async function analyze(useDemo,demoKey='normal'){ $('#analysis-loading').hidden=false; $('#analyze-button').disabled=true; try { const parsed=useDemo?{...(demoReceipts[demoKey]||demoReceipts.normal),imageHash:null,risk:undefined,riskReason:undefined,checks:undefined}:await analyzeWithGemini(); const saved=await api('/api/receipts',{method:'POST',body:JSON.stringify(parsed)});state.pending=saved;state.queue.unshift(saved);if(state.records)state.records.unshift(saved); toast(state.user.role==='admin'?'AI 审核完成，请确认入账。':'收据已提交，管理员会收到通知。'); setView(state.user.role==='admin'?'review':'upload') } catch(err) { toast(err.message||'识别失败，请使用演示收据或检查 API Key。'); $('#analyze-button').disabled=false } finally { $('#analysis-loading').hidden=true; updateDashboard() } }
async function analyzeWithGemini(){ const key=localStorage.getItem('ledgerlens-key'); if(!key) throw new Error('请先在 AI 设置中填写 Gemini API Key，或使用演示收据。'); const [prefix,data]=state.imageData.split(','); const mime=prefix.match(/data:(.*?);/)[1]; const prompt=`You are an accounting receipt extraction assistant for a Malaysian SME. Analyze this receipt image. Return ONLY valid JSON (no markdown) with exactly: vendor (string), date (YYYY-MM-DD or empty), invoiceNumber (string), total (number), tax (number), currency (MYR if Malaysian ringgit), category (one of Travel & Transport, Meals & Entertainment, Office Supplies, Software & Subscriptions, Fixed Assets, Other Expenses), description (short string), confidence (integer 0-100), myinvoisStatus (string), risk (approved, review, or rejected), riskReason (Chinese concise string), checks (array of objects with label Chinese string and type ok/warn/bad). Apply these rules: if a MyInvois UUID or clear QR reference is visible say "Reference detected" otherwise "Not verified"; flag low confidence or suspicious altered totals for review; do not claim legal validation.`; const model=localStorage.getItem('ledgerlens-model')||'gemini-2.5-flash'; const res=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent`,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':key},body:JSON.stringify({contents:[{parts:[{text:prompt},{inline_data:{mime_type:mime,data}}]}],generationConfig:{responseMimeType:'application/json',temperature:0.1}})}); if(!res.ok){const e=await res.json().catch(()=>({}));throw new Error(e.error?.message||'Gemini API 请求失败');} const out=await res.json(); const raw=out.candidates?.[0]?.content?.parts?.[0]?.text; let parsed; try{parsed=JSON.parse(raw)}catch{throw new Error('AI 未返回有效结构化数据，请重试。')} if(!parsed.total||!parsed.vendor)throw new Error('未能从图片读取足够的收据信息。'); parsed.imageHash=await sha256(state.imageData); return parsed }

function renderReviewQueue(){const list=$('#review-queue');const counter=$('#queue-count');if(list)counter&&(counter.textContent=state.queue.length);if(!list)return;list.innerHTML=state.queue.length?state.queue.map(x=>`<button type="button" class="queue-item${state.pending&&x.id===state.pending.id?' selected':''}" data-qid="${x.id}"><span class="q-vendor">${esc(x.vendor)||'未识别商户'}</span><span class="q-meta">${esc(x.date||'无日期')} · ${money(x.total)} · ${categoryLabel(x.category)}</span><span class="status ${x.risk||'review'}">${riskLabel(x)}</span></button>`).join(''):'<p class="empty small">暂无待审核收据，员工提交后会显示在这里。</p>';list.querySelectorAll('.queue-item').forEach(b=>b.addEventListener('click',()=>{const r=state.queue.find(x=>x.id===b.dataset.qid);if(r){state.pending=r;renderReviewQueue();renderReview();}}));}
function renderReview(){ renderReviewQueue(); const has=!!state.pending; $('#review-empty').hidden=has; $('#review-content').hidden=!has; if(!has)return; const x=state.pending; $('#confidence').textContent=(x.confidence||0)+'%'; $('#result-vendor').textContent=x.vendor; $('#extracted-fields').innerHTML=[['日期',x.date||'未识别'],['发票/收据号',x.invoiceNumber||'未识别'],['总额',money(x.total)],['费用类别',categoryLabel(x.category)],['税额',money(x.tax||0)],['MyInvois',x.myinvoisStatus||'Not verified']].map(([a,b])=>`<div class="field"><span>${a}</span><b>${b}</b></div>`).join(''); $('#result-image').innerHTML=state.imageData?`原始凭证（已关联）<img src="${state.imageData}" alt="上传的收据"/>`:'演示模式 · 原始收据会在正式系统中加密保存'; if(x.imageHash)$('#result-image').innerHTML+=`<small class="hash-line">凭证已存证 · SHA-256 ${x.imageHash.slice(0,16)}…</small>`; else $('#result-image').innerHTML+=`<small class="hash-line">凭证哈希：未保存（演示模式，正式系统会加密存储原件与哈希）</small>`; const status=riskLabel(x); $('#review-status').className='status '+x.risk; $('#review-status').textContent=status; $('#risk-summary').textContent=x.riskReason; $('#checks').innerHTML=(x.checks||[]).map(c=>`<div class="check"><span class="check-icon ${c.type}">${c.type==='ok'?'✓':c.type==='warn'?'!':'×'}</span><span>${c.label}</span></div>`).join(''); $('#journal-entry').innerHTML=`<div class="journal-row header"><span>科目</span><span>借方</span><span>贷方</span></div><div class="journal-row"><b>${categoryLabel(x.category)}</b><span>${money(x.total)}</span><span>—</span></div><div class="journal-row"><b>应付账款 / 员工垫款</b><span>—</span><span>${money(x.total)}</span></div><div class="journal-row total"><span>合计</span><span>${money(x.total)}</span><span>${money(x.total)}</span></div>`; }
$('#approve-button').addEventListener('click',async()=>{if(!state.pending)return;await api('/api/receipts/'+state.pending.id,{method:'PATCH',body:JSON.stringify({status:'approved',risk:'approved',postedAt:new Date().toISOString()})});await loadRecords();toast('已确认入账，员工会收到通知。');setView('reports')});
$('#reject-button').addEventListener('click',async()=>{if(!state.pending)return;const reason=prompt('请输入拒绝原因：','缺少可验证的发票信息，请补充原始凭证');if(reason===null)return;await api('/api/receipts/'+state.pending.id,{method:'PATCH',body:JSON.stringify({status:'rejected',risk:'rejected',reason})});await loadRecords();toast('已拒绝，员工会收到原因通知。');setView('dashboard')});
$('#edit-entry').addEventListener('click',()=>{if(!state.pending)return; const choices=['Travel & Transport','Meals & Entertainment','Office Supplies','Software & Subscriptions','Fixed Assets','Other Expenses']; const selected=prompt('输入费用类别：\n'+choices.join('\n'),state.pending.category); if(choices.includes(selected)){state.pending.category=selected;renderReview();toast('会计类别已更新。')}});
function renderMyReceipts(){const list=$('#myreceipts-list');if(!list)return;const rows=state.records||[];list.innerHTML=rows.length?rows.map(x=>`<div class="myreceipt" data-id="${x.id}"><div class="myreceipt-head"><b>${esc(x.vendor)||'未识别商户'}</b><span class="status ${x.status}">${statusLabel(x)}</span></div><div class="myreceipt-meta">${esc(x.date||'无日期')} · ${money(x.total)} · ${categoryLabel(x.category)}<small>${esc(x.invoiceNumber||'无收据号')} · 风险：${riskLabel(x)}${x.uploadedByName?' · 提交人 '+esc(x.uploadedByName):''}</small></div>${x.status==='rejected'?`<div class="myreceipt-reason">管理员意见：${esc(x.reason||'请联系管理员了解原因。')}</div>`:''}<div class="myreceipt-actions">${x.status==='rejected'?`<button type="button" class="text-button resubmit" data-rid="${x.id}">重新提交</button>`:''}${x.imageHash?`<small class="hash-line">存证 ${x.imageHash.slice(0,12)}…</small>`:'<small class="hash-line">演示单据 · 未保存原件</small>'}</div></div>`).join(''):'<p class="empty">你还没有提交过收据，去「上传收据」页试一张。</p>';list.querySelectorAll('.resubmit').forEach(b=>b.addEventListener('click',async()=>{const r=state.records.find(x=>x.id===b.dataset.rid);if(!r)return;if(!confirm(`按原数据重新提交收据「${r.invoiceNumber||r.vendor}」？会创建一张新的待审核单据，请先修正原始凭证。`))return;try{const saved=await api('/api/receipts',{method:'POST',body:JSON.stringify(resubmitable(r))});state.records.unshift(saved);state.queue.unshift(saved);await loadRecords();renderMyReceipts();toast('已重新提交，等待管理员审核。')}catch(e){toast(e.message||'重新提交失败。')}}));}
function renderAdmin(){const stats=$('#admin-stats');const total=$('#admin-total');if(total)total.textContent=(state.records||[]).length;if(!stats)return;const all=state.records||[];stats.innerHTML=`<div class="admin-stat"><span>总单据</span><b>${all.length}</b></div><div class="admin-stat"><span>待审核</span><b>${all.filter(x=>x.status==='pending').length}</b></div><div class="admin-stat"><span>已入账</span><b>${all.filter(x=>x.status==='approved').length}</b></div><div class="admin-stat"><span>已拒绝</span><b>${all.filter(x=>x.status==='rejected').length}</b></div>`;}
$('#reset-data').addEventListener('click',async()=>{const n=(state.records||[]).length;if(!confirm(`确定清空全部 ${n} 条收据与通知？该操作不可恢复（演示版）。`))return;if(!confirm('这是最后确认：点击「确定」将彻底清空演示数据。'))return;try{await api('/api/admin/reset',{method:'POST',body:'{}'});state.pending=null;state.queue=[];state.ledger=[];state.records=[];$('#result-image').innerHTML='';await loadRecords();renderAdmin();if(state.user.role==='admin')setView('dashboard');toast('已清空全部数据。')}catch(e){toast(e.message||'清空失败，仅管理员可执行。')}});
function renderReports(){const total=expenseTotal(),profit=BASE_INCOME-total,payables=total,cash=BASE_CASH-total; $('#report-expenses').textContent=money(total);$('#report-profit').textContent=money(profit);$('#cash-balance').textContent=money(cash);$('#payables').textContent=money(payables);$('#equity').textContent=money(cash-payables);$('#ledger-list').innerHTML=state.ledger.length?state.ledger.map(x=>`<div class="ledger-row"><small>${x.date}</small><span><b>${categoryLabel(x.category)}</b><br/><small>${x.vendor} · 收据 ${x.invoiceNumber||'—'}</small></span><b>${money(x.total)}</b><span class="status approved">已入账</span></div>`).join(''):'<p class="empty">确认收据后，总账条目会显示在这里。</p>'}
$('#open-settings').addEventListener('click',()=>{ $('#api-key').value=localStorage.getItem('ledgerlens-key')||''; $('#model-name').value=localStorage.getItem('ledgerlens-model')||'gemini-2.5-flash'; $('#settings').showModal()}); $('#save-settings').addEventListener('click',()=>{localStorage.setItem('ledgerlens-key',$('#api-key').value.trim());localStorage.setItem('ledgerlens-model',$('#model-name').value.trim());toast('AI 设置已保存。')});
$('#ask-ai').addEventListener('click',()=>{const t=expenseTotal();$('#report-answer').hidden=false;$('#report-answer').innerHTML=`<b>✦ AI 管理层摘要：</b>本月已确认费用 ${money(t)}，使税前净利润降至 ${money(BASE_INCOME-t)}。${t?`主要成本来自「${categoryLabel(state.ledger.sort((a,b)=>b.total-a.total)[0].category)}」。建议老板核对高频支出，并为该类别设置月度预算。`:'目前还没有费用数据；上传并确认收据后，我可以解释利润与现金流变化。'}`});
function exportCsv(){const head=['日期','商户','收据号','费用类别','金额','税额','币种','MyInvois','状态','审核人','入账时间','凭证哈希'];const rows=state.ledger.map(x=>[x.date||'',x.vendor||'',x.invoiceNumber||'',categoryLabel(x.category),String(x.total),String(x.tax||0),x.currency||'MYR',x.myinvoisStatus||'',statusLabel(x),x.reviewedBy||'',x.postedAt||'',x.imageHash||'']);const csv='\ufeff'+[head,...rows].map(r=>r.map(c=>`"${String(c??'').replace(/"/g,'""')}"`).join(',')).join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=`ledgerlens-export-${new Date().toISOString().slice(0,10)}.csv`;document.body.appendChild(a);a.click();a.remove();toast('已导出 CSV，可用 Excel 打开。');}
$('#export-csv').addEventListener('click',exportCsv);
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),3500)}
document.body.classList.add('locked'); updateDashboard(); renderReports();
